version: '3'

services:
  db:
    image: "postgres:14-alpine"
    ports:
      - "6444:5432"
    restart: always
    environment:
      - POSTGRES_USER=timecapsule
      - POSTGRES_PASSWORD=timecapsule
      - POSTGRES_DB=timecapsule
    volumes:
      - ./postgres_data_timecapsule:/var/lib/postgresql/data

volumes:
  postgres_data_timecapsule:
