app:
  version: "1.0.0"
  name: Time Capsule API
  description: "Time Capsule API"
  base-path: /api

api:
  prefix.v1: ${app.base-path}/v1

spring:
  application.name: ${app.name}
  data.rest.base-path: ${app.base-path}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    open-in-view: false

  datasource:
    url: jdbc:postgresql://localhost:6444/timecapsule
    username: timecapsule
    password: timecapsule

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      group-id: time-capsule-group
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
    topics:
      time-capsule-send: time-capsule-send

server:
  port: 8081
  servlet:
    context-path: /
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1
    mime-types: text/html,
      text/xml,
      text/plain,
      text/css,
      text/javascript,
      application/javascript,
      application/json,
      application/xml,
      application/pdf,
      image/png,
      image/jpeg,
      image/svg+xml