app:
  version: "1.0.0"
  name: Time Capsule API
  description: "Time Capsule API"
  base-path: /api

api:
  prefix.v1: ${app.base-path}/v1

spring:
  application.name: ${app.name}
  data.rest.base-path: ${app.base-path}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    open-in-view: false

  datasource:
    url: jdbc:postgresql://localhost:6444/timecapsule
    username: timecapsule
    password: timecapsule

server:
  port: 8080
  servlet:
    context-path: /
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1
    mime-types: text/html,
      text/xml,
      text/plain,
      text/css,
      text/javascript,
      application/javascript,
      application/json,
      application/xml,
      application/pdf,
      image/png,
      image/jpeg,
      image/svg+xml